### ISSUE TITLE
All corresponding Labels are linked wrongly

### ISSUE THREAD

**Issue by suliman-khaan** [jitsi-contrib/jitok#2]
As I visit the Jitok I found the following issues

1. All the Enabled labels are linked to the **lobby-bypass** fields, which should be linked to the corresponding field.
2. Same for the Disabled Labels
3. Don't set labels linked to the **affiliation** fields.

**Comment by emrahcom** [comment]
I cannot reproduce what you said. 

Do you get the same results in [jitok demo](https://jitok.emrah.com/)

**Comment by suliman-khaan** [comment]
[Watch this video](https://www.loom.com/share/ed72bedf469f453cb3a0d4b627bf1fe6) you will get an idea of what I'm trying to say.

**Comment by emrahcom** [comment]
Still I cannot reproduce the same issue.

Is this your own setup? If so, how did you setup?
Which browser is this?
Did you update any codes?

**Comment by suliman-khaan** [comment]
No, It's a live site, and I'm using the Chrome browser, and I didn't update any code.

**Comment by emrahcom** [comment]
Do you mean [jitok.emrah.com](https://jitok.emrah.com/)?

Is there any error in your browser console while testing this issue?

**Comment by suliman-khaan** [comment]
Did you watch the video?

**Comment by emrahcom** [comment]
Yes but it doesn't behave like this in my case

**Comment by suliman-khaan** [comment]
Just click on the label instead of the radio button you will find the issue.

**Comment by suliman-khaan** [comment]
In the label, you have entered the _**for attribute**_ same for all the fields. which makes this issue.

**Comment by emrahcom** [comment]
oh. I see now

**Comment by suliman-khaan** [comment]
That's what I'm trying to say.

**Comment by emrahcom** [comment]
Fixed with https://github.com/jitsi-contrib/jitok/commit/aa2fb23137503597b32e48cc22b9cbf606a60a63

**Comment by suliman-khaan** [comment]
Great job.
