### ISSUE TITLE
dns error

### ISSUE THREAD

**Issue by shuhaib3** [jitsi-contrib/jitok#3]
Looks like URL needs to be changed to https://deno.land/x/djwt@v2.9.1/mod.ts

```error sending request for url (https://deno.land/x/djwt/mod.ts): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution```

**Comment by emrahcom** [comment]
Hi @shuhaib3,

Thank you for the report.

Both links work on my side and I can run `deno` application without changing any code. I tested after deleting my `deno` cache.
