### ISSUE TITLE
Service 'api' failed to build : The command '/bin/sh -c deno cache /app/jitok.ts' returned a non-zero code: 134

### ISSUE THREAD

**Issue by sidney31** [jitsi-contrib/jitok#4]
user@dch-chl-web:~/jitok$ **docker-compose up -d --build** 
Creating network "jitok_default" with the default driver
Building api
Step 1/7 : FROM denoland/deno
 ---> 611c239db0e6
Step 2/7 : WORKDIR /app
 ---> Using cache
 ---> 270b63f13a0c
Step 3/7 : COPY jitok.ts /app/
 ---> Using cache
 ---> 94f5651c22dd
Step 4/7 : RUN deno cache /app/jitok.ts
 ---> Running in 71cd494abf54

Fatal error in , line 0
Check failed: Start().

**#FailureMessage Object: 0x7ffdbcaaca40Aborted (core dumped)
ERROR: Service 'api' failed to build : The command '/bin/sh -c deno cache /app/jitok.ts' returned a non-zero code: 134**

Без выполнения скрипта "/bin/sh -c deno cache /app/jitok.ts'" всё работает.

**Comment by emrahcom** [comment]
I cannot reproduce this issue.

Can you access https://deno.land/std@0.205.0 from this network?

**Comment by sidney31** [comment]
Yes, I have access to this resource from my network.

**Comment by emrahcom** [comment]
I added GitHub workflows to create images in hub and now, `docker-compose` uses these images by default. Can you try again without `--build`

```
docker-compose up -d
```

Then go to `https://127.0.0.1`

**Comment by sidney31** [comment]
Thanks, it works perfectly!
